site_name: LGSVL Simulator

repo_url: https://github.com/lgsvl/simulator
site_author: LG Electronics America R&D Center
site_description: Autonomous driving simulation tool from LG Electronics
site_url: https://www.lgsvlsimulator.com

edit_uri: edit/master/Docs/

docs_dir: docs

theme:
  name: null
  custom_dir: 'theme/' # readthedocs modified
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []

copyright: Copyright &copy; 2019-2020 LG Electronics Inc.

google_analytics: ['UA-130546445-1','lgsvlsimulator.com/docs']

nav:
- 'Home': 'index.md'
- 'Quick start':
  - 'Getting started': 'getting-started.md'
  - 'Keyboard shortcuts': 'keyboard-shortcuts.md'
  - 'Release notes': 'changelog.md'
  - 'Web User Interface':
    - 'Maps': 'maps-tab.md'
    - 'Vehicles': 'vehicles-tab.md'
    - 'Sensor parameters': 'sensor-json-options.md'
    - 'Clusters': 'clusters-tab.md'
    - 'Simulations': 'simulations-tab.md'
  - 'Simulation User Interface':
    - 'Menu items': 'simulation-menu.md'
    - 'Sensor visualization': 'sensor-visualizers.md'
    - 'Bridge topics': 'bridge-connection-ui.md'
  - 'Configuration File and Command Line Parameters': 'config-and-cmd-line-params.md'
- 'Integration with AD':
  - 'Running with Autoware.AI':
    - 'Instructions': 'autoware-instructions.md'
    - 'Sample sensor configuration': 'autoware-json-example.md'
  - 'Running with Autoware.Auto':
    - 'Instructions': 'autoware-auto-instructions.md'
    - 'Sample sensor configuration': 'autoware-auto-json-example.md'
  - 'Running with latest Apollo':
    - 'Instructions': 'apollo-master-instructions.md'
  - 'Running with Apollo 5.0':
    - 'Instructions': 'apollo5-0-instructions.md'
    - 'Sample sensor configuration': 'apollo5-0-json-example.md'
  - 'Running with Apollo 3.0':
    - 'Instructions': 'apollo-instructions.md'
    - 'Sample sensor configuration': 'apollo-json-example.md'
  - 'LGSVL ROS/ROS2 Message Definitions':
    - 'The lgsvl_msgs package': 'lgsvl-msgs.md'
    - 'Ground truth obstacles':
      - 'Viewing and subscribing to ground truth data': 'perception-ground-truth.md'
      - 'Sample sensor configuration for data collection': 'ground-truth-json-example.md'
- 'Python API':
  - 'Python API guide': 'python-api.md'
  - 'Python API quickstart examples': 'api-quickstart-descriptions.md'
  - 'Python API use case examples': 'api-example-descriptions.md'
  - 'How to run a scenario' : 'api-how-to-run-scenario.md'
- 'Tutorials':
  - 'Reinforcement learning with OpenAI Gym': 'openai-gym.md'
  - 'Deep Learning lane following model': 'lane-following.md'
  - 'How to create a simple ROS2-based AD stack': 'create-ros2-ad-stack.md'
  - 'How to collect data with control calibration sensor': 'control-calibration.md'
- 'Advanced':
  - 'Supported message types': 'simulator-messages.md'
  - 'Map annotation': 'map-annotation.md'
  - 'Build instructions': 'build-instructions.md'
  - 'Adding assets': 'assets.md'
  - 'Adding a new map': 'add-new-map.md'
  - 'Adding a new ego vehicle': 'add-new-ego-vehicle.md'
  - 'NPC map navigation': 'npc-map-navigation.md'
  - 'Plugins': 
    - 'Sensor plugins': 'sensor-plugins.md'
    - 'Bridge plugins': 'bridge-plugins.md'
    - 'Lidar sensor plugin': 'lidar-plugin.md'
    - 'Controllable plugins': 'controllable-plugins.md'
    - 'Traffic behavior plugins': 'npc-plugins.md'
    - 'Vehicle dynamics': 'ego-vehicle-dynamics.md'
  - 'Point cloud':
    - 'Point cloud import': 'pointcloud-import.md'
    - 'Point cloud rendering': 'pointcloud-rendering.md'
  - 'Unity help': 'unity-help.md'
- 'Support':
  - 'FAQ': 'faq.md'
  - 'Contributing': 'contributing.md'

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: "2-4"
    - attr_list
    - wikilinks:
        base_url: "#"
        end_url: ""

extra_css:
  - css/extra.css

extra_javascript:
    - 'javascripts/clipboard.js'
    - 'javascripts/copy-to-clipboard.js'
